
package com.sulake.habbo.navigator.events
{
    public class HabboNavigatorTrackingEvent 
    {

        public static const HABBO_NAVIGATOR_TRACKING_EVENT_CLOSED:String = "HABBO_NAVIGATOR_TRACKING_EVENT_CLOSED";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_EVENTS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_EVENTS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_ROOMS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_ROOMS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_ME:String = "HABBO_NAVIGATOR_TRACKING_EVENT_ME";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCH:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCH";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_OFFICIAL:String = "HABBO_NAVIGATOR_TRACKING_EVENT_OFFICIAL";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_LATEST_EVENTS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_LATEST_EVENTS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FAVOURITES:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FAVOURITES";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FRIENDS_ROOMS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FRIENDS_ROOMS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_HISTORY:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_HISTORY";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_ROOMS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_ROOMS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_OFFICIALROOMS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_OFFICIALROOMS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_POPULAR_ROOMS:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_POPULAR_ROOMS";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TAG_SEARCH:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TAG_SEARCH";
        public static const HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TEXT_SEARCH:String = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TEXT_SEARCH";

    }
}//package com.sulake.habbo.navigator.events

// HabboNavigatorTrackingEvent = "_-0Vu" (String#15273, DoABC#2)


